### ISSUE TITLE
Align and define branch-strategy

### ISSUE THREAD

**Issue by codeDavidLopez** [amosproj/amos2022ss06-idunion-blockchain-dashboard#10]
## Purpose
1. As a developer
2. I want / need branching and merging strategy
3. So that commits and the code are organized

## Involved team members
* all developers

## Affected artifacs
* planning document
* architecture description
* board
* ...

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by codeDavidLopez** [comment]
Estimation: 2

**Comment by julianrosenberger** [comment]
(rules for commit and push)

**Comment by codeDavidLopez** [comment]
Strategy written and merged in the base. Real estimation: 1
