### ISSUE TITLE
Add min. 1 new KPI to the metrics engine

### ISSUE THREAD

**Issue by codeDavidLopez** [amosproj/amos2022ss06-idunion-blockchain-dashboard#39]
## User story
1. As a user
2. I want / need a new KPI (not yet available)
3. So that more information about the network and ledger is available

## Acceptance criteria
* minimum 1 new KPI defined (a information not yet available), suggestions here: https://github.com/amosproj/amos2022ss06-idunion-blockchain-dashboard/tree/main/indy-node-monitor/fetch-validator-status#extracting-useful-information
* New KPI calculated with metrics engine
* New KPI stored in Prometeus.io
* New KPI available for the Grafana Dashboard

## Feature DoD 
* Feature has been fully implemented
* All acceptance criteria were met
* All tests are passing
* No known errors
* Documentation updated
* Bill of materials updated

## Sprint Release DoD
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Peer code review passed
* Developers agreed to release
* Documentation updated
* Bill of materials updated

**Comment by A-Sandrini** [comment]
not finished in sprint 6

**Comment by A-Sandrini** [comment]
re-estimation = 8
