### ISSUE TITLE
Define basic architecture for the project

### ISSUE THREAD

**Issue by codeDavidLopez** [amosproj/amos2022ss06-idunion-blockchain-dashboard#5]
## User story
1. As a team member
2. I want / need more details about the technical implementation
3. So that the features can be assigned to an system element and work easier distributed

## Acceptance criteria
* Reasonable break-down of system in at least two sub-systems (e.g. ledger and dashboard)
* Elements in the architecture have different functions
* UML-notation used

## Definition of done (DoD)
* Architecture provides more details to allocate features

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by A-Sandrini** [comment]
Estimation: 3

**Comment by codeDavidLopez** [comment]
Feature demonstrated in the review. Acceptance criteria meet. Real estimation is: 5
