### ISSUE TITLE
Saving the dashboard in Grafana

### ISSUE THREAD

**Issue by A-Sandrini** [amosproj/amos2022ss06-idunion-blockchain-dashboard#65]
## User story
1. As a developer
2. I want / need to save the dashboard in Grafana
3. So that I do not have to import json files or rebuild the dashboard

## Acceptance criteria
* The changes should be stored in the repository

## Definition of done (DoD)
* Every user can use the same Grafana configuration

## Feature DoD 
* Feature has been fully implemented
* All acceptance criteria were met
* All tests are passing
* No known errors
* Documentation updated
* Bill of materials updated

## Sprint Release DoD
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Peer code review passed
* Developers agreed to release
* Documentation updated
* Bill of materials updated

**Comment by codeDavidLopez** [comment]
done
