### ISSUE TITLE
Update documentation concerning shell script

### ISSUE THREAD

**Issue by A-Sandrini** [amosproj/amos2022ss06-idunion-blockchain-dashboard#66]
## User story
1. As a developer
2. I want / need instructions in the documentation to implement the shell script 
3. So that I know how to implement it

## Acceptance criteria
* Documentation updated concerning the shell script

## Feature DoD 
* Feature has been fully implemented
* All acceptance criteria were met
* All tests are passing
* No known errors
* Documentation updated
* Bill of materials updated

## Sprint Release DoD
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Peer code review passed
* Developers agreed to release
* Documentation updated
* Bill of materials updated

**Comment by codeDavidLopez** [comment]
remark of @A-Sandrini : login as separate step necessary; @murali-kri5hna : manual step mandatory currently as user role is not stored with creds in the config file. **Idea** for future feature: store creds in config file or setup script
