### ISSUE TITLE
Extend fetch validator script to local json files

### ISSUE THREAD

**Issue by A-Sandrini** [amosproj/amos2022ss06-idunion-blockchain-dashboard#73]
## User story
1. As a developer
2. I want / need the fetch validator script extended
3. So that I can extract data from a local json file 

## Acceptance criteria
* Data from json files from industry partner can be extracted with the fetch validator script (json file can be found here: https://faubox.rrze.uni-erlangen.de/getlink/fi715pnEj7PPdtv2zsxgbF4x/)
* Data stored in prometheus

## Definition of done (DoD)
* local json file can be analyzed

## Feature DoD 
* Feature has been fully implemented
* All acceptance criteria were met
* All tests are passing
* No known errors
* Documentation updated
* Bill of materials updated

## Sprint Release DoD
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Peer code review passed
* Developers agreed to release
* Documentation updated
* Bill of materials updated

**Comment by codeDavidLopez** [comment]
For better application, a separate script is provided "convert_json_to_prometheus.py".
