### ISSUE TITLE
Showcase Grafana

### ISSUE THREAD

**Issue by codeDavidLopez** [amosproj/amos2022ss06-idunion-blockchain-dashboard#9]
## User story
1. As a user
2. I want / need a dashboard
3. So that i can read the data (find out basic information about the ledger)

## Acceptance criteria
* Define (static or dynamic) example data (either some data-base or maybe more simple a data-file)
* Display example data in Grafana
* Describe the interface to Prometeus

## Definition of done (DoD)
* Grafana example set up
* bill of materials updated
* interfaces documented

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by codeDavidLopez** [comment]
Grafana example displayed with the default data example. The interface to Prometeus.io is built-in and out-of-the-box available as a plug-in in Grafana. Bill of materials is updated and interface described in the Prometeus.io documentation / plug-in docu of Grafana.

**Comment by A-Sandrini** [comment]
Real estimation: ~5
